USE DataWarehouseAnalytics;

/*
STEP 1 DATABASE EXPLORATION : 
*/

--(a) EXPLORE ALL TABLES IN DATABASE 

SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- (b) EXPLORE ALL COLUMNS FROM SPECIFIC TABLE IN DATABASE
SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'dim_customers';

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'dim_products';

SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'fact_sales';

/*
STEP 2
DIMENSIONS EXPLORATION: 
(a) EXPLORE ALL COUNTRIES WE HAVE OUR CUSTOMERS IN
*/

SELECT DISTINCT country
FROM gold.dim_customers
	ORDER BY country;


-- (b) EXPLORE ALL PRODUCT CATEGORIES
SELECT DISTINCT category, subcategory, product_name
FROM gold.dim_products
	ORDER BY 1,2,3;

/*
STEP 3 DATE EXPLORATION:
*/

-- (a) DATE OF FIRST AND LAST ORDER AND THE TIMESPAN AS WELL

SELECT
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(YEAR, MIN(order_date), MAX(order_date))
		AS timespan
FROM gold.fact_sales;

-- (b) FIND THE YOUNGEST AND THE OLDEST CUSTOMER
SELECT 
	MIN(birthdate) AS oldest_customer,
	DATEDIFF(YEAR, MIN(birthdate), GETDATE())
		AS oldest_age,
	MAX(birthdate) AS youngest_customer,
	DATEDIFF(YEAR, MAX(birthdate), GETDATE())
		AS youngest_age
FROM gold.dim_customers; 


/*
STEP 4 MEASURES EXPLORATION:
*/

SELECT * FROM gold.fact_sales;
SELECT * FROM gold.dim_products;

-- (a) FIND TOTAL SALES
SELECT SUM(sales_amount) AS total_sales
FROM gold.fact_sales ;

-- HOW MANY ITEMS ARE SOLD?
SELECT COUNT(quantity) AS item_sold
FROM gold.fact_sales;

-- WHAT'S THE AVERAGE SELLING PRICE
SELECT AVG(price) AS avg_price
FROM gold.fact_sales;

-- FIND TOTAL NUMBER OF ORDERS
SELECT COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales;


-- FIND TOTAL NUMBER OF PRODUCTS
SELECT COUNT(DISTINCT product_key) AS product_count
FROM gold.dim_products;


-- FIND TOP 3 CUSTOMERS WITH MOST ORDERS PLACED
SELECT TOP 3 
	customer_key,
	COUNT(order_number) AS number_of_orders
FROM gold.fact_sales
	GROUP BY customer_key
	ORDER BY number_of_orders DESC;


-- FIND TOTAL NUMBER OF CUSTOMERS
SELECT COUNT(customer_key) AS total_customers
FROM gold.dim_customers;


-- FIND TOTAL CUSTOMERS WHO HAVE PLACED AN ORDER
SELECT 
	COUNT(DISTINCT customer_key) AS customers_count_with_orders
FROM gold.fact_sales;


-- SHOW ALL KEY METRICS AT ONCE

SELECT 'Total_sales' AS Measure_name, SUM(sales_amount) AS Measure_value FROM gold.fact_sales 
UNION ALL
SELECT 'Average_price' AS Measure_name, AVG(price) AS Measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Item_sold' AS Measure_name, COUNT(quantity) AS Measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total_orders' AS Measure_name, COUNT(DISTINCT order_number) AS Measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total_Customers' AS Measure_name, COUNT(customer_key) AS Measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Total_products' AS Measure_name, COUNT(DISTINCT product_key) AS Measure_value FROM gold.dim_products;


/*
STEP 5 MAGNITUDE ANALYSIS :
*/

-- (a) FIND TOTAL CUSTOMERS PER COUNTRY
SELECT 
	Country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY Country
ORDER BY total_customers DESC;


--(b) FIND TOTAL MALE AND FEMALE POPULATION IN CUSTOMERS
SELECT 
	Gender,
	COUNT(Gender) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;


-- (c) FIND TOTAL PRODUCTS PER CATEGORY
SELECT 
	Category,
	COUNT(product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;


-- (d) FIND AVERAGE COST IN EACH CATEGORY

SELECT 
	category,
	AVG(cost) AS average_cost 
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;


-- (e) FIND TOTAL REVENUE GENERATED BY EACH CATEGORY

SELECT 
	p.category,
	SUM(s.sales_amount) AS revenue
FROM gold.fact_sales AS s
	LEFT JOIN gold.dim_products AS p
	ON s.product_key = p.product_key
GROUP BY p.category
ORDER BY revenue DESC;


-- (f) TOTAL REVENUE GENERATED BY EACH CUSTOMER

SELECT 
	s.customer_key,
	c.first_name,
	c.last_name,
	SUM(s.sales_amount) AS revenue
FROM gold.fact_sales AS s
	LEFT JOIN gold.dim_customers AS c
	ON s.customer_key = c.customer_key
GROUP BY s.customer_key, c.first_name, c.last_name
ORDER BY revenue DESC;


-- (g) DISRTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES

SELECT 
	c.country,
	COUNT(s.product_key) AS Number_of_sold_items
FROM gold.fact_sales AS s
	LEFT JOIN gold.dim_customers AS c
	ON s.customer_key = c.customer_key
GROUP BY c.country
ORDER BY Number_of_sold_items DESC;

/*
STEP 6 RANKING ANALYSIS :
*/

--(a) TOP 5 HIGHEST REVENUE GENERATING PRODUCTS

SELECT TOP 5 
	f.product_key,d.product_name, 
	COUNT(f.product_key) AS items_sold, 
	SUM(f.sales_amount) AS revenue_generated
FROM gold.fact_sales AS f
	LEFT JOIN gold.dim_products AS d
	ON f.product_key = d.product_key
GROUP BY f.product_key, d.product_name
ORDER BY revenue_generated DESC ;

-- (b) 5 WORST PERFORMING PRODUCTS 

SELECT TOP 5 
	f.product_key,d.product_name, 
	COUNT(f.product_key) AS items_sold, 
	SUM(f.sales_amount) AS revenue_generated
FROM gold.fact_sales AS f
	LEFT JOIN gold.dim_products AS d
	ON f.product_key = d.product_key
GROUP BY f.product_key, d.product_name
ORDER BY revenue_generated ASC ;

--(c) TOP 5 REVENUE GENERATING CUSTOMERS 

SELECT TOP 5 s.customer_key, c.first_name, c.last_name ,SUM(s.sales_amount) AS revenue
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON s.customer_key = c.customer_key
GROUP BY s.customer_key,c.first_name, c.last_name
ORDER BY revenue DESC;

--(d) CUSTOMERS WITH FEWEST ORDERS PLACED


SELECT TOP 5 s.customer_key,c.first_name, c.last_name, COUNT(DISTINCT s.order_number) AS orders_placed
FROM gold.fact_sales AS s
LEFT JOIN gold.dim_customers AS c
ON s.customer_key = c.customer_key
GROUP BY  s.customer_key, c.first_name, c.last_name
ORDER BY orders_placed ASC;

--ANY FEEDBACKS, SUGGESTIONS, ADVICES ARE WELCOMED 
-- Email : anshukumar65524@gmail.com